### PR TITLE
Fix peer transfer of CID v1

### LINKED ISSUE #199: Error when you try to download/delete a v1 CID from another peer
### steps

1. download a CID from a miner in Browser A
1. request the CID from Browser B
1. download CID from peer (not proxy)

### expected

CID to be transferred

### actual

Key not found in database

### notes

Likely issue: incorrect parameters on `datastore.put`, need to decode CID as in the proxy transfer

### PR DESCRIPTION
**Pull request by brunolm**
Closes #199 

cid-v1-peer

### CODE REVIEW

File: src/shared/retrieval-market/Client.ts [hunk 1]
```diff
@@ -53,6 +55,24 @@ export class Client {
...
+    )
+
+    let importOptions = undefined
+
+    if (decoded.version === 1) {
+      importOptions = {
+        cidVersion: decoded.version,
+        hashAlg: decoded.hashAlg,
+        rawLeaves: true,
+        maxChunkSize: 1048576,
```
Comment (aistoc) [inline src/shared/retrieval-market/Client.ts]: Better to define the hardcoded values in `decodeCID.ts` and import them to `SocketClient.ts` and `Client.ts`.

File: src/shared/retrieval-market/Client.ts [hunk 2]
```diff
@@ -53,6 +55,24 @@ export class Client {
...
+        maxChildrenPerNode: 1024,
```
Comment (aistoc) [inline src/shared/retrieval-market/Client.ts]: Same as the above comment.

**Review by aistoc — APPROVED** [review]
